{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Values.global.namespace }}
  labels:
{{- include "lab4-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
{{- include "lab4-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8090
  type: {{ .Values.nginx.service.type }}
{{- end }}