{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Values.global.namespace }}
  labels:
{{- include "lab4-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
{{- include "lab4-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
{{- include "lab4-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources:
{{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
        - name: nginx-html
          configMap:
            name: {{ .Release.Name }}-nginx-config
            items:
              - key: index.html
                path: index.html
{{- end }}
